# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_OPTIONS = "--no-experimental-fetch"
  NODE_ENV = "production"
  NPM_CONFIG_OPTIONAL = "false"
  NPM_FLAGS = "--omit=optional"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/insight-tip"
  to = "/.netlify/functions/insight-tip"
  status = 200
  force = true
   from = "/api/stripe/webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
  force = true

  [build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = ""   # falls Netlify irgendwo '--production' gesetzt hatte
