# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_OPTIONS = "--no-experimental-fetch"
  NODE_ENV = "production"
  NPM_CONFIG_OPTIONAL = "false"
  NPM_FLAGS = "--omit=optional"
