[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/insight-tip"
  to = "/.netlify/functions/insight-tip"
  status = 200
  force = true

[[redirects]]
  from = "/api/stripe/webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
  force = true

